<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.1 (Python 3.10.7 on win32)" generated="20221119 11:51:24.115" rpa="false" schemaversion="3">
<suite id="s1" name="P1901 DDT Excel" source="C:\development\robot-scripts\Automation\TestCases\P1901_DDT_Excel.robot">
<kw name="Open my browser" library="P1802_LoginResources" type="SETUP">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${LOGIN URL}</arg>
<arg>${BROWSER}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20221119 11:51:24.431" level="INFO">Opening browser 'chrome' to base url 'https://admin-demo.nopcommerce.com/'.</msg>
<status status="PASS" starttime="20221119 11:51:24.416" endtime="20221119 11:51:27.364"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20221119 11:51:27.364" endtime="20221119 11:51:27.488"/>
</kw>
<status status="PASS" starttime="20221119 11:51:24.416" endtime="20221119 11:51:27.488"/>
</kw>
<test id="s1-t1" name="LoginTestWithExcel using" line="14">
<kw name="Invalid login">
<arg>${username}</arg>
<arg>${password}</arg>
<msg timestamp="20221119 11:51:27.488" level="FAIL">Variable '${username}' not found.</msg>
<status status="FAIL" starttime="20221119 11:51:27.488" endtime="20221119 11:51:27.488"/>
</kw>
<status status="FAIL" starttime="20221119 11:51:27.488" endtime="20221119 11:51:27.488">Variable '${username}' not found.</status>
</test>
<status status="FAIL" starttime="20221119 11:51:24.131" endtime="20221119 11:51:27.488"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="P1901 DDT Excel">P1901 DDT Excel</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221119 11:51:24.416" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\development\robot-scripts\Automation\TestCases\P1901_DDT_Excel.robot", line 0</msg>
<msg timestamp="20221119 11:51:24.416" level="ERROR">In source file:
  File ".../TestData/LoginData.xlsx", line 0</msg>
<msg timestamp="20221119 11:51:24.416" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\development\robot-scripts\Automation\TestCases\.../TestData/LoginData.xlsx but file does not exist.</msg>
</errors>
</robot>
